version: "3.9"

#################################
# ğŸ…±ğŸ…°ğŸ†‚ğŸ…´ ğŸ…¸ğŸ…¼ğŸ…°ğŸ…¶ğŸ…´
#  - generates the base image needed for individual training tasks
#
#  - ğŸ†ğŸ†„ğŸ…½: docker-compose -f docker-compose-build-base.yaml build
#################################

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: ma-lederer-base
    